---
- hosts: localhost
- 
  become: true
  become_method: sudo
  hosts: localhost
  name: "Tomcat deployment playbook"
  remote_user: root
  roles: 
    - tomcat
  vars: 
    tomcat_ver: "9.0.30"
    ui_admin_pass: admin
    ui_admin_username: admin
    ui_manager_pass: admin
    ui_manager_user: admin
